import LogoutButton from "@/components/LogoutButton"
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs"
import { cookies } from "next/headers"
import "./globals.css"
import Link from "next/link"
import DeployButton from "@/components/DeployButton"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  const supabase = createServerComponentClient({ cookies })

  const {
    data: { user }
  } = await supabase.auth.getUser()

  return (
    <body>
      <main>
        <nav>
          {user ? (
            <div className="flex items-center gap-4">
              Hey, {user.email}!
              <LogoutButton />
            </div>
          ) : (
            <Link href="/login">Login</Link>
          )}
        </nav>
        {children}
      </main>
    </body>
  )
}
