import LogoutButton from "@/components/LogoutButton"
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs"
import { cookies } from "next/headers"
import "./globals.css"
import Link from "next/link"
import Button from "@mui/material/Button"
import AppBar from "@mui/material/AppBar"
import Toolbar from "@mui/material/Toolbar"
import Typography from "@mui/material/Typography"
import DeployButton from "@/components/DeployButton"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  const supabase = createServerComponentClient({ cookies })

  const {
    data: { user }
  } = await supabase.auth.getUser()

  return (
    <body>
      <AppBar position="static">
        <Toolbar>
          <Typography
            variant="h6"
            component="div"
            sx={{ flexGrow: 1 }}
          >
            {user ? (
              <div>{user.email}</div>
            ) : (
              <Button
                color="inherit"
                href="/login"
              >
                Login
              </Button>
            )}
          </Typography>
          <Button
            color="inherit"
            href="/"
          >
            Home
          </Button>
          <Button
            color="inherit"
            href="/todo"
          >
            Todo
          </Button>
        </Toolbar>
      </AppBar>
      <main>
        <nav>
          {user ? (
            <div className="flex items-center gap-4">
              <LogoutButton />
            </div>
          ) : (
            <p>Please log in with your account!</p>
          )}
        </nav>
        {children}
      </main>
    </body>
  )
}
